


name: Monday → Discord Notifications

on:
  schedule:
    # Runs every 5 minutes
    - cron: "*/5 * * * *"
  workflow_dispatch:  # allow manual runs

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv

      - name: Run Monday → Discord script
        working-directory: ./scripts
        env:
          MONDAY_API_KEY: ${{ secrets.MONDAY_API_KEY }}
          MONDAY_BOARD_ID: ${{ secrets.MONDAY_BOARD_ID }}
          DISCORD_GENERAL_WEBHOOK: ${{ secrets.DISCORD_GENERAL_WEBHOOK }}
          DISCORD_BUSINESS_WEBHOOK: ${{ secrets.DISCORD_BUSINESS_WEBHOOK }}
          DISCORD_EDUCATION_WEBHOOK: ${{ secrets.DISCORD_EDUCATION_WEBHOOK }}
          DISCORD_ENGINEERING_WEBHOOK: ${{ secrets.DISCORD_ENGINEERING_WEBHOOK }}
          DISCORD_FINANCE_WEBHOOK: ${{ secrets.DISCORD_FINANCE_WEBHOOK }}
          DISCORD_IT_WEBHOOK: ${{ secrets.DISCORD_IT_WEBHOOK }}
          DISCORD_LAW_WEBHOOK: ${{ secrets.DISCORD_LAW_WEBHOOK }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
        run: python monday_to_discord.py
